"""initial schema

Revision ID: d466ce6143af
Revises:
Create Date: 2026-09-10 10:18:34.520228

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d466ce6143af"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fetch_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("target", sa.String(length=300), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("rows", sa.Integer(), nullable=True),
        sa.Column("ok", sa.Boolean(), nullable=False),
        sa.Column("error", sa.String(length=1000), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "film",
        sa.Column("tmdb_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("original_title", sa.String(length=300), nullable=True),
        sa.Column("us_theatrical_date", sa.Date(), nullable=True),
        sa.Column("runtime_minutes", sa.Integer(), nullable=True),
        sa.Column("director", sa.String(length=200), nullable=True),
        sa.Column("cast_top", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("poster_path", sa.String(length=200), nullable=True),
        sa.Column("refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("tmdb_id"),
    )
    op.create_table(
        "theatre",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("source_theatre_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("chain", sa.String(length=100), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("lat", sa.Float(), nullable=True),
        sa.Column("lng", sa.Float(), nullable=True),
        sa.Column("distance_miles", sa.Float(), nullable=True),
        sa.Column("tracked", sa.Boolean(), nullable=False),
        sa.Column("is_favourite", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "source_theatre_id"),
    )
    op.create_table(
        "film_alias",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tmdb_id", sa.Integer(), nullable=False),
        sa.Column("alias_normalized", sa.String(length=300), nullable=False),
        sa.Column("origin", sa.String(length=16), nullable=False),
        sa.ForeignKeyConstraint(["tmdb_id"], ["film.tmdb_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tmdb_id", "alias_normalized"),
    )
    op.create_table(
        "film_state",
        sa.Column("tmdb_id", sa.Integer(), nullable=False),
        sa.Column("earliest_date_anywhere", sa.Date(), nullable=True),
        sa.Column("earliest_theatre_id", sa.Integer(), nullable=True),
        sa.Column("earliest_date_at_fav", sa.Date(), nullable=True),
        sa.Column("earliest_fav_theatre_id", sa.Integer(), nullable=True),
        sa.Column("is_watchlist", sa.Boolean(), nullable=False),
        sa.Column("is_rerelease", sa.Boolean(), nullable=False),
        sa.Column("alerted_new_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("alerted_fav_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("alerted_earlier_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("alerted_earliest_date", sa.Date(), nullable=True),
        sa.Column("alerted_soon_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_seen_showing", sa.Date(), nullable=True),
        sa.Column("last_computed", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["earliest_fav_theatre_id"],
            ["theatre.id"],
        ),
        sa.ForeignKeyConstraint(
            ["earliest_theatre_id"],
            ["theatre.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tmdb_id"],
            ["film.tmdb_id"],
        ),
        sa.PrimaryKeyConstraint("tmdb_id"),
    )
    op.create_table(
        "source_film",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("source_film_id", sa.String(length=64), nullable=False),
        sa.Column("raw_title", sa.String(length=300), nullable=False),
        sa.Column("raw_year", sa.Integer(), nullable=True),
        sa.Column("film_url", sa.String(length=500), nullable=True),
        sa.Column("runtime_minutes", sa.Integer(), nullable=True),
        sa.Column("director", sa.String(length=200), nullable=True),
        sa.Column("cast_top", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("tmdb_id", sa.Integer(), nullable=True),
        sa.Column("resolution", sa.String(length=16), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("enriched_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tmdb_id"],
            ["film.tmdb_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "source_film_id"),
    )
    op.create_table(
        "watchlist_entry",
        sa.Column("letterboxd_slug", sa.String(length=200), nullable=False),
        sa.Column("title_raw", sa.String(length=300), nullable=False),
        sa.Column("year_raw", sa.Integer(), nullable=True),
        sa.Column("tmdb_id", sa.Integer(), nullable=True),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("removed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["tmdb_id"],
            ["film.tmdb_id"],
        ),
        sa.PrimaryKeyConstraint("letterboxd_slug"),
    )
    op.create_table(
        "match_queue",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_film_id", sa.Integer(), nullable=False),
        sa.Column("candidates", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["source_film_id"], ["source_film.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_film_id"),
    )
    op.create_table(
        "showing",
        sa.Column("source_film_id", sa.Integer(), nullable=False),
        sa.Column("theatre_id", sa.Integer(), nullable=False),
        sa.Column("show_date", sa.Date(), nullable=False),
        sa.Column("show_times", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("first_seen", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["source_film_id"], ["source_film.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["theatre_id"], ["theatre.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("source_film_id", "theatre_id", "show_date"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("showing")
    op.drop_table("match_queue")
    op.drop_table("watchlist_entry")
    op.drop_table("source_film")
    op.drop_table("film_state")
    op.drop_table("film_alias")
    op.drop_table("theatre")
    op.drop_table("film")
    op.drop_table("fetch_log")
    # ### end Alembic commands ###
